### ISSUE TITLE
Contrato

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-proyecto-contrato-inteligente-entrevista-ar#1]
[Contrato1.pdf](https://github.com/user-attachments/files/18084943/Contrato1.pdf)

**Comment by AmilkarVladimiR** [comment]
Portada y escudos institucionales: 25 puntos
Incluye objetivos: 25 puntos
Tiene descripción clara: 25 puntos
Contiene resultados y conclusión: 25 puntos
Porcentaje obtenido 100% = 50 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado..
